### ISSUE TITLE
Allow gift card codes to be attached to a customer

### ISSUE THREAD

**Issue by brettflorio** [Foxy/foxy-elements#100]
Gift card codes can be attached to a customer either via a `customer_id` (integer) or the `._links["fx:customer"].href` (URL) value on the gift card code resource.

We'll want to allow this to be handled from the elements. For now, if we can accept the ID, the email (which we can get the ID from, as there'll only ever be 1 non-guest customer per email), or the full URL (back-end API URL, though we could conceivably pull the ID from the new admin URL if it'd make sense), that'd be good.

**Comment by brettflorio** [comment]
Note: This isn't documented in the API docs yet but will be on the next deploy.

**Comment by pheekus** [comment]
Released in v1.27.0
