### ISSUE TITLE
Accessing Individual Shipping Options in admin stalls browser

### ISSUE THREAD

**Issue by rijarobinson** [Foxy/foxy-elements#134]
Accessing individual shipping options in admin crashes browser. User reported this issue and we reproduced in Firefox, Chrome, and Safari. To reproduce, log into admin and select **Settings->Shipping**.  Selecting Custom Shipping Code seems to reproduce it always for me, but if I select a few different options one after the other, it may freeze up as well.

**Comment by pheekus** [comment]
This turned out to be an admin issue. Partially fixed (the page no longer freezes) but some weirdness may remain until the hAPI fix for the missing slash in shipping hrefs is deployed.
