### ISSUE TITLE
`foxy-customer-portal`: Update subscription summary total to pull from `transaction_template` instead of `last_transaction`

### ISSUE THREAD

**Issue by rijarobinson** [Foxy/foxy-elements#136]
User reported that the subscriptions show the last order total in the summary list (260.86): 
<img width="860" alt="image" src="https://github.com/Foxy/foxy-elements/assets/17171225/0d56cc48-f88d-4fa6-96ae-b31cb16963bf">

Perhaps we should be just showing the subscription amount there (100.88)?
<img width="233" alt="image" src="https://github.com/Foxy/foxy-elements/assets/17171225/98418a4c-c06f-4ff9-84f2-d9f996231e69">

**Comment by adamjudd** [comment]
Yes, we should switch this to use the `transaction_template` instead of the `last_transaction`. If a store modifies a subscription, then it's not reflected in summary list for the portal until the subscription renews.
