### ISSUE TITLE
Coupons: Add UI for new customer attributes / subscription based restrictions

### ISSUE THREAD

**Issue by brettflorio** [Foxy/foxy-elements#138]

**Comment by pheekus** [comment]
@brettflorio I think those are already there? Or is it something else? <img width="730" alt="Captura de pantalla 2023-10-20 a la(s) 16 28 53" src="https://github.com/Foxy/foxy-elements/assets/47783757/5bd0b347-0ab3-4327-bdd9-a7d7feea98d1">

**Comment by brettflorio** [comment]
Oops :)
