### ISSUE TITLE
Can't reset or set subscription end date

### ISSUE THREAD

**Issue by joshbartolomucci** [Foxy/foxy-elements#153]
If an end date has already been set for a subscription, it's not possible to clear it or change it.

foxy-subscription-form element

**Comment by rijarobinson** [comment]
Just adding to this since it's the same form. No end date on the sub shows as December 31, 1969.

<img width="600" alt="image" src="https://github.com/user-attachments/assets/41a3ef03-3892-47c1-bba7-ce524f1c75c9">
