### ISSUE TITLE
Subscription card element shows current total order price instead of future order total for future starting subscriptions

### ISSUE THREAD

**Issue by jesusmpds** [Foxy/foxy-elements#192]
Future starting subscriptions are a little weird on the portal. The $0/28days kind of makes you think 0 it's actually what you will pay instead of the price of the item.

![image](https://github.com/user-attachments/assets/c783eaa5-71a3-41b2-aee6-70abc3441e0a)

For a future sub, the today total will indeed be $0, but there will be a future order total attribute. According to Adam.

**Comment by adamjudd** [comment]
Closing for https://github.com/Foxy/foxy-elements/issues/157
