### ISSUE TITLE
`foxy-items-form` adding `sub_modify` and `sub_restart` at the item (not the cart) level

### ISSUE THREAD

**Issue by brettflorio** [Foxy/foxy-elements#24]
Related to #11, possibly https://github.com/Foxy/foxy-elements/pull/12/commits/d2fd62c901306e293cd4e7dfa865c87f86bd99a6

Currently, when working with subscription items, _every item_ gets the `sub_modify=replace` and `sub_restart=auto` options added, prefixed with the digit. These params need to be passed to `/cart` just once, without any prefixes. So currently if you inspect the POST in the dev tools, you'll see something like this:
```
10:name: Fancy Widget
10:code: 1003
10:price: 27.94
10:image: https://foo.tld/bar.png
10:quantity: 1
10:sub_frequency: 30d
10:sub_modify: replace
10:sub_restart: auto
// ...
11:sub_modify: replace
11:sub_restart: auto
// etc, these params added per item
cart: checkout
```

That _should_ look like this:
```
sub_modify: replace
sub_restart: auto
cart: checkout
```

**Comment by ndvo** [comment]
Is it correct to say that the same is valid for sub_frequency, sub_startdate, sub_enddate, sub_token?
