### ISSUE TITLE
Explain the "public" visibility on attribute creation, according to context

### ISSUE THREAD

**Issue by brettflorio** [Foxy/foxy-elements#25]
![image](https://user-images.githubusercontent.com/34131/110445925-7eb02700-8073-11eb-84fb-02a7e0877d65.png)

On creating a new attribute, let's make sure the "public" ("everyone" in the screenshot above) setting clearly explains the impact, based on the attribute's parent resource. For instance, the text could read as follows, for these resources:

* Customers: "The customer"
* Transactions: "The customer"
* Store: "The world, public"

Actually, it should be "The customer" (or better, equivalent wording) for everything but attributes on the `store` resource.

**Comment by ndvo** [comment]
Is this on the main branch? Couldn't find it in the storybook and it seems the english translations that are showing on the picture are not in the code base (of course they could be dynamically built...).
