### ISSUE TITLE
 `foxy-payment-method-card`: Null cc_type causes payment method section error

### ISSUE THREAD

**Issue by rijarobinson** [Foxy/foxy-elements#60]
Some payment method resources may have null in the `cc_type`, which doesn't appear to be accounted for in this version. As a result, the payment method card fails to render.
<img width="951" alt="image" src="https://user-images.githubusercontent.com/17171225/131177511-fb8f1273-23fa-429d-ad4f-95b54743c2b1.png">

**Comment by pheekus** [comment]
Uuuuuh not quite closed yet :)
