### ISSUE TITLE
`foxy-dialog-window`: Consider increasing default z-index

### ISSUE THREAD

**Issue by adamjudd** [Foxy/foxy-elements#68]
We recently landed on a default `z-index` of `1000` for the `foxy-dialog-window` element, which is a decent default. We've already been foiled though, as Bootstrap uses a default for their varying elements between `1000` and `1080`: https://getbootstrap.com/docs/5.0/layout/z-index/.

Considering the popularity of Bootstrap, we should probably use a default that's higher than theirs. Obviously we'll always have something higher, and people can customise with CSS, but at least being higher than Bootstrap makes sense to me.

**Comment by pheekus** [comment]
Another thing: I've just noticed that Vaadin's combo box overlay has a `z-index` of `200`. It doesn't cause any trouble in Chrome, but in Safari any combo box in a form dialog will display the overlay behind the dialog window.

**Comment by brettflorio** [comment]
Let's just set the z-index to…
![one million!](https://media.makeameme.org/created/one-million-3jg3jt.jpg)

**Comment by pheekus** [comment]
Closing this because we can't make `z-index` of dialog windows greater than `200` since `vaadin-combo-box` uses that value for its overlay and many of our dialog forms use `vaadin-combo-box`.

If this value is too low for your project, add this to your global CSS:

```css
vaadin-combo-box-overlay,
foxy-dialog-window {
  z-index: 9999; /* or whatever works for you */
}
```
