### ISSUE TITLE
📊 `foxy-reports`: elements to work with the new reporting resources

### ISSUE THREAD

**Issue by brettflorio** [Foxy/foxy-elements#83]
The `reports` collection has recently been added, documented here: https://api.foxycart.com/rels/reports

The resources are fairly bare, so the collection page should probably use a full-width table element. There's no real need for a card display for an individual report, but the one unique thing about report resources is the `_links["fx:download_url"]` is short lived (currently 10 minutes), so there's a chance the link won't work when clicked. To avoid this, I propose the following:

1. Output a collection table that includes a download link. This link _should not_ point to the `fx:download_url`. (Alternately, instead of a download column, it could be a status column, where a status of "ready" outputs the download link.)
2. On click of the download link, a GET to the specific resource should be made, and the fresh `_links["fx:download_url"]` value should be downloaded at that time.

This ensure the links will always work, even if the user doesn't click on them until >10min after pageload.

**Comment by pheekus** [comment]
Released in 1.17.0
