### ISSUE TITLE
Email Templates: add collection, improve resources UI

### ISSUE THREAD

**Issue by brettflorio** [Foxy/foxy-elements#86]
We already have the `EmailTemplateForm`, but we'll be using those email templates for a bit more with some new functionality (new emailer system allowing for flexible templating and [MJML](https://mjml.io/); gift card purchasing + provisioning), so we'll need to allow the `email_templates` collection to be displayed, and to add and modify additional `email_template` resources.

Additionally, the `email_template` resources will have a new `template_language` parameter with the following values: 
```
"pug", "nunjucks", "handlebars", "twig", "ejs"
```

Further, some new email templates will allow for MJML to be used.

At a minimum and for now, we need the ability to list templates, display templates, and edit templates.

While we're modifying these elements, let's also look into the possibility of adding a live preview of the email template. This should allow data population from preset samples (email receipt, gift card gift recipient email, abandoned cart reminders) or from specific transactions, and rendering of the templates using the selected template language and MJML. Adding previews might be too much at this point, but would be a huge improvement if it's possible.

**Comment by pheekus** [comment]
This has been added in the new admin a while ago.
