### ISSUE TITLE
Item Category collection and resource UI

### ISSUE THREAD

**Issue by brettflorio** [Foxy/foxy-elements#87]
Related to https://github.com/Foxy/foxy-elements/issues/86 and gift card provisioning (app#5993).

For normal functionality, as well as to support gift card auto-provisioning (ie. being able to sell gift cards, provision them, and notify a gift recipient), we'll need UI for [`item_categories`](https://api.foxycart.com/rels/item_categories).

Notes:
* The `discount_` parameters should probably reuse UI from the coupon (and gift card) elements (currently [still in beta](https://github.com/Foxy/foxy-elements/blob/beta/src/elements/public/CouponForm/CouponForm.ts)).
* The `_email` templates will include `gift_recipient_` params (in addition to `admin_` and `customer_`). Unlike the current admin, the actual template UI (subject, html template, text template, etc.) should _not_ be on this page. Instead, each email template should present a selection of existing email templates to associate. (To create new templates will be done via #86.)

**Comment by pheekus** [comment]
Already exists in the new admin ("Categories" page, this repo also has `foxy-item-category-form` and `foxy-item-category-card`).
